### ISSUE TITLE
Create_Environment job in java cartridge fails

### ISSUE THREAD

**Issue by kramos** [Accenture/adop-cartridge-java-environment-template#6]
due to tomcat:8.0 no longer being tagged on dockerhub
```
Pulling tomcat (tomcat:8.0)...
8.0: Pulling from library/tomcat
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by dsingh07** [comment]
@kramos I'm not sure if I'm looking in the right place, but I can see the tag here? https://hub.docker.com/r/library/tomcat/tags/8.0/

**Comment by kramos** [comment]
Seems like dockerhub re-added the tag!  Sorry for wasting your time.
